package com.example.empty.infrastructure.persistence.po;

import java.util.Date;

public class CascadeBase {
    /**
     * 
     */
    private String datasetid;

    /**
     * 目录id
     */
    private String cataId;

    /**
     * 目录分类id
     */
    private String groupId;

    /**
     * 数据资源目录名称
     */
    private String cataTitle;

    /**
     * 信息资源编码
     */
    private String catacode;

    /**
     * 资源格式分类 01,电子文件02,电子表格03,数据库04,图形图像05,流媒体06,自描述格式
     */
    private String resourceformat;

    /**
     * 资源格式分类 0310,mysql
     */
    private String resourceformattype;

    /**
     * 发布日期
     */
    private Date publishedtime;

    /**
     * 1：无条件共享2：有条件共享3：不予共享'
     */
    private String sharedType;

    /**
     * 共享方式类型编码,0101 接口,0102 数据库,0103 文件
     */
    private String sharedway;

    /**
     * 开放类型（1：可对社会开放，2：不可对社会开放；3：部分对社会开放）
     */
    private Integer openType;

    /**
     * 数据更新周期 2：每日,3：每周,4：每月,5：每季度,6：每半年,7：每年,8：实时,1：其他
     */
    private String updateCycle;

    /**
     * 默认4  目录状态
     */
    private Integer status;

    /**
     * 记录修改时间
     */
    private Date mateUpdatetime;

    /**
     * 数据资源id
     */
    private String resourceId;

    /**
     * 机构id
     */
    private String orgid;

    /**
     * 1库表，2文件
     */
    private String resourceType;

    /**
     * resource_type为1时填表名,resource_type为2时填文件名
     */
    private String resourceInstance;

    /**
     * 是否启动 1启用 0暂停 -1初始化导入 2 取消级联中
     */
    private String isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.datasetid
     *
     * @return the value of t_dl_cascade_cata.datasetid
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getDatasetid() {
        return datasetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.datasetid
     *
     * @param datasetid the value for t_dl_cascade_cata.datasetid
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setDatasetid(String datasetid) {
        this.datasetid = datasetid == null ? null : datasetid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.cata_id
     *
     * @return the value of t_dl_cascade_cata.cata_id
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.cata_id
     *
     * @param cataId the value for t_dl_cascade_cata.cata_id
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setCataId(String cataId) {
        this.cataId = cataId == null ? null : cataId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.group_id
     *
     * @return the value of t_dl_cascade_cata.group_id
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.group_id
     *
     * @param groupId the value for t_dl_cascade_cata.group_id
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.cata_title
     *
     * @return the value of t_dl_cascade_cata.cata_title
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getCataTitle() {
        return cataTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.cata_title
     *
     * @param cataTitle the value for t_dl_cascade_cata.cata_title
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setCataTitle(String cataTitle) {
        this.cataTitle = cataTitle == null ? null : cataTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.catacode
     *
     * @return the value of t_dl_cascade_cata.catacode
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getCatacode() {
        return catacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.catacode
     *
     * @param catacode the value for t_dl_cascade_cata.catacode
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setCatacode(String catacode) {
        this.catacode = catacode == null ? null : catacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.resourceformat
     *
     * @return the value of t_dl_cascade_cata.resourceformat
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getResourceformat() {
        return resourceformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.resourceformat
     *
     * @param resourceformat the value for t_dl_cascade_cata.resourceformat
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setResourceformat(String resourceformat) {
        this.resourceformat = resourceformat == null ? null : resourceformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.resourceformattype
     *
     * @return the value of t_dl_cascade_cata.resourceformattype
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getResourceformattype() {
        return resourceformattype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.resourceformattype
     *
     * @param resourceformattype the value for t_dl_cascade_cata.resourceformattype
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setResourceformattype(String resourceformattype) {
        this.resourceformattype = resourceformattype == null ? null : resourceformattype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.publishedtime
     *
     * @return the value of t_dl_cascade_cata.publishedtime
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public Date getPublishedtime() {
        return publishedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.publishedtime
     *
     * @param publishedtime the value for t_dl_cascade_cata.publishedtime
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setPublishedtime(Date publishedtime) {
        this.publishedtime = publishedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.shared_type
     *
     * @return the value of t_dl_cascade_cata.shared_type
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getSharedType() {
        return sharedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.shared_type
     *
     * @param sharedType the value for t_dl_cascade_cata.shared_type
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setSharedType(String sharedType) {
        this.sharedType = sharedType == null ? null : sharedType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.sharedway
     *
     * @return the value of t_dl_cascade_cata.sharedway
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getSharedway() {
        return sharedway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.sharedway
     *
     * @param sharedway the value for t_dl_cascade_cata.sharedway
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setSharedway(String sharedway) {
        this.sharedway = sharedway == null ? null : sharedway.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.open_type
     *
     * @return the value of t_dl_cascade_cata.open_type
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public Integer getOpenType() {
        return openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.open_type
     *
     * @param openType the value for t_dl_cascade_cata.open_type
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setOpenType(Integer openType) {
        this.openType = openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.update_cycle
     *
     * @return the value of t_dl_cascade_cata.update_cycle
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getUpdateCycle() {
        return updateCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.update_cycle
     *
     * @param updateCycle the value for t_dl_cascade_cata.update_cycle
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setUpdateCycle(String updateCycle) {
        this.updateCycle = updateCycle == null ? null : updateCycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.status
     *
     * @return the value of t_dl_cascade_cata.status
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.status
     *
     * @param status the value for t_dl_cascade_cata.status
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.mate_updatetime
     *
     * @return the value of t_dl_cascade_cata.mate_updatetime
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public Date getMateUpdatetime() {
        return mateUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.mate_updatetime
     *
     * @param mateUpdatetime the value for t_dl_cascade_cata.mate_updatetime
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setMateUpdatetime(Date mateUpdatetime) {
        this.mateUpdatetime = mateUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.resource_id
     *
     * @return the value of t_dl_cascade_cata.resource_id
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.resource_id
     *
     * @param resourceId the value for t_dl_cascade_cata.resource_id
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId == null ? null : resourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.orgid
     *
     * @return the value of t_dl_cascade_cata.orgid
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.orgid
     *
     * @param orgid the value for t_dl_cascade_cata.orgid
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.resource_type
     *
     * @return the value of t_dl_cascade_cata.resource_type
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.resource_type
     *
     * @param resourceType the value for t_dl_cascade_cata.resource_type
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.resource_instance
     *
     * @return the value of t_dl_cascade_cata.resource_instance
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getResourceInstance() {
        return resourceInstance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.resource_instance
     *
     * @param resourceInstance the value for t_dl_cascade_cata.resource_instance
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setResourceInstance(String resourceInstance) {
        this.resourceInstance = resourceInstance == null ? null : resourceInstance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.is_enable
     *
     * @return the value of t_dl_cascade_cata.is_enable
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.is_enable
     *
     * @param isEnable the value for t_dl_cascade_cata.is_enable
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable == null ? null : isEnable.trim();
    }
}