package com.example.empty.infrastructure.persistence.po;

public class CascadeBaseWithBLOBs extends CascadeBase {
    /**
     * 资源摘要
     */
    private String description;

    /**
     * json格式字段描述
     */
    private String columnlist;

    /**
     * 共享条件
     */
    private String sharedCondition;

    /**
     * 开放条件（对向社会开放资源的条件描述。如无条件，请填写无）
     */
    private String openCondition;

    /**
     * 资源名称
     */
    private String resourceName;

    /**
     * 
     */
    private String tableColumns;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.description
     *
     * @return the value of t_dl_cascade_cata.description
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.description
     *
     * @param description the value for t_dl_cascade_cata.description
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.columnlist
     *
     * @return the value of t_dl_cascade_cata.columnlist
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getColumnlist() {
        return columnlist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.columnlist
     *
     * @param columnlist the value for t_dl_cascade_cata.columnlist
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setColumnlist(String columnlist) {
        this.columnlist = columnlist == null ? null : columnlist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.shared_condition
     *
     * @return the value of t_dl_cascade_cata.shared_condition
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getSharedCondition() {
        return sharedCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.shared_condition
     *
     * @param sharedCondition the value for t_dl_cascade_cata.shared_condition
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setSharedCondition(String sharedCondition) {
        this.sharedCondition = sharedCondition == null ? null : sharedCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.open_condition
     *
     * @return the value of t_dl_cascade_cata.open_condition
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getOpenCondition() {
        return openCondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.open_condition
     *
     * @param openCondition the value for t_dl_cascade_cata.open_condition
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setOpenCondition(String openCondition) {
        this.openCondition = openCondition == null ? null : openCondition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.resource_name
     *
     * @return the value of t_dl_cascade_cata.resource_name
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.resource_name
     *
     * @param resourceName the value for t_dl_cascade_cata.resource_name
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dl_cascade_cata.table_columns
     *
     * @return the value of t_dl_cascade_cata.table_columns
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getTableColumns() {
        return tableColumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dl_cascade_cata.table_columns
     *
     * @param tableColumns the value for t_dl_cascade_cata.table_columns
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setTableColumns(String tableColumns) {
        this.tableColumns = tableColumns == null ? null : tableColumns.trim();
    }
}