package com.example.empty.infrastructure.persistence.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CascadeBaseExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public CascadeBaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andDatasetidIsNull() {
            addCriterion("datasetid is null");
            return (Criteria) this;
        }

        public Criteria andDatasetidIsNotNull() {
            addCriterion("datasetid is not null");
            return (Criteria) this;
        }

        public Criteria andDatasetidEqualTo(String value) {
            addCriterion("datasetid =", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidNotEqualTo(String value) {
            addCriterion("datasetid <>", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidGreaterThan(String value) {
            addCriterion("datasetid >", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidGreaterThanOrEqualTo(String value) {
            addCriterion("datasetid >=", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidLessThan(String value) {
            addCriterion("datasetid <", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidLessThanOrEqualTo(String value) {
            addCriterion("datasetid <=", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidLike(String value) {
            addCriterion("datasetid like", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidNotLike(String value) {
            addCriterion("datasetid not like", value, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidIn(List<String> values) {
            addCriterion("datasetid in", values, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidNotIn(List<String> values) {
            addCriterion("datasetid not in", values, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidBetween(String value1, String value2) {
            addCriterion("datasetid between", value1, value2, "datasetid");
            return (Criteria) this;
        }

        public Criteria andDatasetidNotBetween(String value1, String value2) {
            addCriterion("datasetid not between", value1, value2, "datasetid");
            return (Criteria) this;
        }

        public Criteria andCataIdIsNull() {
            addCriterion("cata_id is null");
            return (Criteria) this;
        }

        public Criteria andCataIdIsNotNull() {
            addCriterion("cata_id is not null");
            return (Criteria) this;
        }

        public Criteria andCataIdEqualTo(String value) {
            addCriterion("cata_id =", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdNotEqualTo(String value) {
            addCriterion("cata_id <>", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdGreaterThan(String value) {
            addCriterion("cata_id >", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdGreaterThanOrEqualTo(String value) {
            addCriterion("cata_id >=", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdLessThan(String value) {
            addCriterion("cata_id <", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdLessThanOrEqualTo(String value) {
            addCriterion("cata_id <=", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdLike(String value) {
            addCriterion("cata_id like", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdNotLike(String value) {
            addCriterion("cata_id not like", value, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdIn(List<String> values) {
            addCriterion("cata_id in", values, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdNotIn(List<String> values) {
            addCriterion("cata_id not in", values, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdBetween(String value1, String value2) {
            addCriterion("cata_id between", value1, value2, "cataId");
            return (Criteria) this;
        }

        public Criteria andCataIdNotBetween(String value1, String value2) {
            addCriterion("cata_id not between", value1, value2, "cataId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andCataTitleIsNull() {
            addCriterion("cata_title is null");
            return (Criteria) this;
        }

        public Criteria andCataTitleIsNotNull() {
            addCriterion("cata_title is not null");
            return (Criteria) this;
        }

        public Criteria andCataTitleEqualTo(String value) {
            addCriterion("cata_title =", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleNotEqualTo(String value) {
            addCriterion("cata_title <>", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleGreaterThan(String value) {
            addCriterion("cata_title >", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleGreaterThanOrEqualTo(String value) {
            addCriterion("cata_title >=", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleLessThan(String value) {
            addCriterion("cata_title <", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleLessThanOrEqualTo(String value) {
            addCriterion("cata_title <=", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleLike(String value) {
            addCriterion("cata_title like", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleNotLike(String value) {
            addCriterion("cata_title not like", value, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleIn(List<String> values) {
            addCriterion("cata_title in", values, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleNotIn(List<String> values) {
            addCriterion("cata_title not in", values, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleBetween(String value1, String value2) {
            addCriterion("cata_title between", value1, value2, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCataTitleNotBetween(String value1, String value2) {
            addCriterion("cata_title not between", value1, value2, "cataTitle");
            return (Criteria) this;
        }

        public Criteria andCatacodeIsNull() {
            addCriterion("catacode is null");
            return (Criteria) this;
        }

        public Criteria andCatacodeIsNotNull() {
            addCriterion("catacode is not null");
            return (Criteria) this;
        }

        public Criteria andCatacodeEqualTo(String value) {
            addCriterion("catacode =", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeNotEqualTo(String value) {
            addCriterion("catacode <>", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeGreaterThan(String value) {
            addCriterion("catacode >", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeGreaterThanOrEqualTo(String value) {
            addCriterion("catacode >=", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeLessThan(String value) {
            addCriterion("catacode <", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeLessThanOrEqualTo(String value) {
            addCriterion("catacode <=", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeLike(String value) {
            addCriterion("catacode like", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeNotLike(String value) {
            addCriterion("catacode not like", value, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeIn(List<String> values) {
            addCriterion("catacode in", values, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeNotIn(List<String> values) {
            addCriterion("catacode not in", values, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeBetween(String value1, String value2) {
            addCriterion("catacode between", value1, value2, "catacode");
            return (Criteria) this;
        }

        public Criteria andCatacodeNotBetween(String value1, String value2) {
            addCriterion("catacode not between", value1, value2, "catacode");
            return (Criteria) this;
        }

        public Criteria andResourceformatIsNull() {
            addCriterion("resourceformat is null");
            return (Criteria) this;
        }

        public Criteria andResourceformatIsNotNull() {
            addCriterion("resourceformat is not null");
            return (Criteria) this;
        }

        public Criteria andResourceformatEqualTo(String value) {
            addCriterion("resourceformat =", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatNotEqualTo(String value) {
            addCriterion("resourceformat <>", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatGreaterThan(String value) {
            addCriterion("resourceformat >", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatGreaterThanOrEqualTo(String value) {
            addCriterion("resourceformat >=", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatLessThan(String value) {
            addCriterion("resourceformat <", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatLessThanOrEqualTo(String value) {
            addCriterion("resourceformat <=", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatLike(String value) {
            addCriterion("resourceformat like", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatNotLike(String value) {
            addCriterion("resourceformat not like", value, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatIn(List<String> values) {
            addCriterion("resourceformat in", values, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatNotIn(List<String> values) {
            addCriterion("resourceformat not in", values, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatBetween(String value1, String value2) {
            addCriterion("resourceformat between", value1, value2, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformatNotBetween(String value1, String value2) {
            addCriterion("resourceformat not between", value1, value2, "resourceformat");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeIsNull() {
            addCriterion("resourceformattype is null");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeIsNotNull() {
            addCriterion("resourceformattype is not null");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeEqualTo(String value) {
            addCriterion("resourceformattype =", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeNotEqualTo(String value) {
            addCriterion("resourceformattype <>", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeGreaterThan(String value) {
            addCriterion("resourceformattype >", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeGreaterThanOrEqualTo(String value) {
            addCriterion("resourceformattype >=", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeLessThan(String value) {
            addCriterion("resourceformattype <", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeLessThanOrEqualTo(String value) {
            addCriterion("resourceformattype <=", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeLike(String value) {
            addCriterion("resourceformattype like", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeNotLike(String value) {
            addCriterion("resourceformattype not like", value, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeIn(List<String> values) {
            addCriterion("resourceformattype in", values, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeNotIn(List<String> values) {
            addCriterion("resourceformattype not in", values, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeBetween(String value1, String value2) {
            addCriterion("resourceformattype between", value1, value2, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andResourceformattypeNotBetween(String value1, String value2) {
            addCriterion("resourceformattype not between", value1, value2, "resourceformattype");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeIsNull() {
            addCriterion("publishedtime is null");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeIsNotNull() {
            addCriterion("publishedtime is not null");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeEqualTo(Date value) {
            addCriterionForJDBCDate("publishedtime =", value, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("publishedtime <>", value, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeGreaterThan(Date value) {
            addCriterionForJDBCDate("publishedtime >", value, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("publishedtime >=", value, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeLessThan(Date value) {
            addCriterionForJDBCDate("publishedtime <", value, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("publishedtime <=", value, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeIn(List<Date> values) {
            addCriterionForJDBCDate("publishedtime in", values, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("publishedtime not in", values, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("publishedtime between", value1, value2, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andPublishedtimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("publishedtime not between", value1, value2, "publishedtime");
            return (Criteria) this;
        }

        public Criteria andSharedTypeIsNull() {
            addCriterion("shared_type is null");
            return (Criteria) this;
        }

        public Criteria andSharedTypeIsNotNull() {
            addCriterion("shared_type is not null");
            return (Criteria) this;
        }

        public Criteria andSharedTypeEqualTo(String value) {
            addCriterion("shared_type =", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeNotEqualTo(String value) {
            addCriterion("shared_type <>", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeGreaterThan(String value) {
            addCriterion("shared_type >", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeGreaterThanOrEqualTo(String value) {
            addCriterion("shared_type >=", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeLessThan(String value) {
            addCriterion("shared_type <", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeLessThanOrEqualTo(String value) {
            addCriterion("shared_type <=", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeLike(String value) {
            addCriterion("shared_type like", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeNotLike(String value) {
            addCriterion("shared_type not like", value, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeIn(List<String> values) {
            addCriterion("shared_type in", values, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeNotIn(List<String> values) {
            addCriterion("shared_type not in", values, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeBetween(String value1, String value2) {
            addCriterion("shared_type between", value1, value2, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedTypeNotBetween(String value1, String value2) {
            addCriterion("shared_type not between", value1, value2, "sharedType");
            return (Criteria) this;
        }

        public Criteria andSharedwayIsNull() {
            addCriterion("sharedway is null");
            return (Criteria) this;
        }

        public Criteria andSharedwayIsNotNull() {
            addCriterion("sharedway is not null");
            return (Criteria) this;
        }

        public Criteria andSharedwayEqualTo(String value) {
            addCriterion("sharedway =", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayNotEqualTo(String value) {
            addCriterion("sharedway <>", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayGreaterThan(String value) {
            addCriterion("sharedway >", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayGreaterThanOrEqualTo(String value) {
            addCriterion("sharedway >=", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayLessThan(String value) {
            addCriterion("sharedway <", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayLessThanOrEqualTo(String value) {
            addCriterion("sharedway <=", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayLike(String value) {
            addCriterion("sharedway like", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayNotLike(String value) {
            addCriterion("sharedway not like", value, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayIn(List<String> values) {
            addCriterion("sharedway in", values, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayNotIn(List<String> values) {
            addCriterion("sharedway not in", values, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayBetween(String value1, String value2) {
            addCriterion("sharedway between", value1, value2, "sharedway");
            return (Criteria) this;
        }

        public Criteria andSharedwayNotBetween(String value1, String value2) {
            addCriterion("sharedway not between", value1, value2, "sharedway");
            return (Criteria) this;
        }

        public Criteria andOpenTypeIsNull() {
            addCriterion("open_type is null");
            return (Criteria) this;
        }

        public Criteria andOpenTypeIsNotNull() {
            addCriterion("open_type is not null");
            return (Criteria) this;
        }

        public Criteria andOpenTypeEqualTo(Integer value) {
            addCriterion("open_type =", value, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeNotEqualTo(Integer value) {
            addCriterion("open_type <>", value, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeGreaterThan(Integer value) {
            addCriterion("open_type >", value, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("open_type >=", value, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeLessThan(Integer value) {
            addCriterion("open_type <", value, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeLessThanOrEqualTo(Integer value) {
            addCriterion("open_type <=", value, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeIn(List<Integer> values) {
            addCriterion("open_type in", values, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeNotIn(List<Integer> values) {
            addCriterion("open_type not in", values, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeBetween(Integer value1, Integer value2) {
            addCriterion("open_type between", value1, value2, "openType");
            return (Criteria) this;
        }

        public Criteria andOpenTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("open_type not between", value1, value2, "openType");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleIsNull() {
            addCriterion("update_cycle is null");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleIsNotNull() {
            addCriterion("update_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleEqualTo(String value) {
            addCriterion("update_cycle =", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleNotEqualTo(String value) {
            addCriterion("update_cycle <>", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleGreaterThan(String value) {
            addCriterion("update_cycle >", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleGreaterThanOrEqualTo(String value) {
            addCriterion("update_cycle >=", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleLessThan(String value) {
            addCriterion("update_cycle <", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleLessThanOrEqualTo(String value) {
            addCriterion("update_cycle <=", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleLike(String value) {
            addCriterion("update_cycle like", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleNotLike(String value) {
            addCriterion("update_cycle not like", value, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleIn(List<String> values) {
            addCriterion("update_cycle in", values, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleNotIn(List<String> values) {
            addCriterion("update_cycle not in", values, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleBetween(String value1, String value2) {
            addCriterion("update_cycle between", value1, value2, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andUpdateCycleNotBetween(String value1, String value2) {
            addCriterion("update_cycle not between", value1, value2, "updateCycle");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeIsNull() {
            addCriterion("mate_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeIsNotNull() {
            addCriterion("mate_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeEqualTo(Date value) {
            addCriterion("mate_updatetime =", value, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeNotEqualTo(Date value) {
            addCriterion("mate_updatetime <>", value, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeGreaterThan(Date value) {
            addCriterion("mate_updatetime >", value, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mate_updatetime >=", value, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeLessThan(Date value) {
            addCriterion("mate_updatetime <", value, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("mate_updatetime <=", value, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeIn(List<Date> values) {
            addCriterion("mate_updatetime in", values, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeNotIn(List<Date> values) {
            addCriterion("mate_updatetime not in", values, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("mate_updatetime between", value1, value2, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andMateUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("mate_updatetime not between", value1, value2, "mateUpdatetime");
            return (Criteria) this;
        }

        public Criteria andResourceIdIsNull() {
            addCriterion("resource_id is null");
            return (Criteria) this;
        }

        public Criteria andResourceIdIsNotNull() {
            addCriterion("resource_id is not null");
            return (Criteria) this;
        }

        public Criteria andResourceIdEqualTo(String value) {
            addCriterion("resource_id =", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotEqualTo(String value) {
            addCriterion("resource_id <>", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdGreaterThan(String value) {
            addCriterion("resource_id >", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("resource_id >=", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLessThan(String value) {
            addCriterion("resource_id <", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLessThanOrEqualTo(String value) {
            addCriterion("resource_id <=", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdLike(String value) {
            addCriterion("resource_id like", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotLike(String value) {
            addCriterion("resource_id not like", value, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdIn(List<String> values) {
            addCriterion("resource_id in", values, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotIn(List<String> values) {
            addCriterion("resource_id not in", values, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdBetween(String value1, String value2) {
            addCriterion("resource_id between", value1, value2, "resourceId");
            return (Criteria) this;
        }

        public Criteria andResourceIdNotBetween(String value1, String value2) {
            addCriterion("resource_id not between", value1, value2, "resourceId");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNull() {
            addCriterion("orgid is null");
            return (Criteria) this;
        }

        public Criteria andOrgidIsNotNull() {
            addCriterion("orgid is not null");
            return (Criteria) this;
        }

        public Criteria andOrgidEqualTo(String value) {
            addCriterion("orgid =", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotEqualTo(String value) {
            addCriterion("orgid <>", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThan(String value) {
            addCriterion("orgid >", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidGreaterThanOrEqualTo(String value) {
            addCriterion("orgid >=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThan(String value) {
            addCriterion("orgid <", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLessThanOrEqualTo(String value) {
            addCriterion("orgid <=", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidLike(String value) {
            addCriterion("orgid like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotLike(String value) {
            addCriterion("orgid not like", value, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidIn(List<String> values) {
            addCriterion("orgid in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotIn(List<String> values) {
            addCriterion("orgid not in", values, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidBetween(String value1, String value2) {
            addCriterion("orgid between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andOrgidNotBetween(String value1, String value2) {
            addCriterion("orgid not between", value1, value2, "orgid");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNull() {
            addCriterion("resource_type is null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIsNotNull() {
            addCriterion("resource_type is not null");
            return (Criteria) this;
        }

        public Criteria andResourceTypeEqualTo(String value) {
            addCriterion("resource_type =", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotEqualTo(String value) {
            addCriterion("resource_type <>", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThan(String value) {
            addCriterion("resource_type >", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("resource_type >=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThan(String value) {
            addCriterion("resource_type <", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLessThanOrEqualTo(String value) {
            addCriterion("resource_type <=", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeLike(String value) {
            addCriterion("resource_type like", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotLike(String value) {
            addCriterion("resource_type not like", value, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeIn(List<String> values) {
            addCriterion("resource_type in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotIn(List<String> values) {
            addCriterion("resource_type not in", values, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeBetween(String value1, String value2) {
            addCriterion("resource_type between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceTypeNotBetween(String value1, String value2) {
            addCriterion("resource_type not between", value1, value2, "resourceType");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceIsNull() {
            addCriterion("resource_instance is null");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceIsNotNull() {
            addCriterion("resource_instance is not null");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceEqualTo(String value) {
            addCriterion("resource_instance =", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceNotEqualTo(String value) {
            addCriterion("resource_instance <>", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceGreaterThan(String value) {
            addCriterion("resource_instance >", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceGreaterThanOrEqualTo(String value) {
            addCriterion("resource_instance >=", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceLessThan(String value) {
            addCriterion("resource_instance <", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceLessThanOrEqualTo(String value) {
            addCriterion("resource_instance <=", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceLike(String value) {
            addCriterion("resource_instance like", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceNotLike(String value) {
            addCriterion("resource_instance not like", value, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceIn(List<String> values) {
            addCriterion("resource_instance in", values, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceNotIn(List<String> values) {
            addCriterion("resource_instance not in", values, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceBetween(String value1, String value2) {
            addCriterion("resource_instance between", value1, value2, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andResourceInstanceNotBetween(String value1, String value2) {
            addCriterion("resource_instance not between", value1, value2, "resourceInstance");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNull() {
            addCriterion("is_enable is null");
            return (Criteria) this;
        }

        public Criteria andIsEnableIsNotNull() {
            addCriterion("is_enable is not null");
            return (Criteria) this;
        }

        public Criteria andIsEnableEqualTo(String value) {
            addCriterion("is_enable =", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotEqualTo(String value) {
            addCriterion("is_enable <>", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThan(String value) {
            addCriterion("is_enable >", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableGreaterThanOrEqualTo(String value) {
            addCriterion("is_enable >=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThan(String value) {
            addCriterion("is_enable <", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLessThanOrEqualTo(String value) {
            addCriterion("is_enable <=", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableLike(String value) {
            addCriterion("is_enable like", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotLike(String value) {
            addCriterion("is_enable not like", value, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableIn(List<String> values) {
            addCriterion("is_enable in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotIn(List<String> values) {
            addCriterion("is_enable not in", values, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableBetween(String value1, String value2) {
            addCriterion("is_enable between", value1, value2, "isEnable");
            return (Criteria) this;
        }

        public Criteria andIsEnableNotBetween(String value1, String value2) {
            addCriterion("is_enable not between", value1, value2, "isEnable");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}