spring:
  application:
    name: empty
  mybatis:
    typeAliasesPackage: com.example.empty.infrastructure.persistence.po
    mapperLocations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
  datasource:
    url: jdbc:mysql://49.7.59.236:3306/dl_user_finally?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: cwovEll__

server:
  port: 8081

redis:
    cluster:
      nodes: 10.150.27.191:9001,10.150.27.191:9002,10.150.27.192:9001,10.150.27.192:9002,10.150.27.193:9001,10.150.27.193:9002      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
      # 最大建立连接等待时间
      maxWaitMillis: 100000

threadPool:
  corePoolSize: 50
  maxPoolSize: 80
  queueCapacity: 9999
  keepAliveSeconds: 60