server:
  port: 8081

spring:
  application:
    name: empty

  mybatis:
    typeAliasesPackage: com.example.empty.infrastructure.persistence.po
    mapperLocations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true

  datasource:
    url: jdbc:mysql://10.20.5.6:3306/dl_user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: cwovEll__

redis:
  host: 10.20.5.6 # Redis服务器地址
  port: 8001 # Redis服务器连接端口
  password: # Redis服务器连接密码（默认为空）
  timeout: 0 # 连接超时时间（毫秒）
  database: 0 # Redis数据库索引（默认为0）
  pool:
    max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 8 # 连接池中的最大空闲连接
    min-idle: 0 # 连接池中的最小空闲连接
  cluster: # redis 集群
    nodes: 10.20.5.6:8001,10.20.5.6:8002,10.20.5.6:8003,10.20.5.6:8004,10.20.5.6:8005,10.20.5.6:8006