spring:
  cloud:
    consul:
      #是否启用consul注册中心,默认不启用
      enabled: false
      #consul 节点
      host: 192.168.56.151
      #http端口
      port: 8500
      discovery:
        #注册 到CONSUL的IP
        ip-address: 127.0.0.1
        #使用IP地址注册而不是域名
        prefer-ip-address: true
        #是否注册到consul,默认不注册
        enabled: false
