package com.example.empty.infrastructure.persistence.mapper;

import com.example.empty.infrastructure.persistence.po.CascadeBase;
import com.example.empty.infrastructure.persistence.po.CascadeBaseExample;
import com.example.empty.infrastructure.persistence.po.CascadeBaseWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CascadeBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    long countByExample(CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int deleteByExample(CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int deleteByPrimaryKey(String datasetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int insert(CascadeBaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int insertSelective(CascadeBaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    List<CascadeBaseWithBLOBs> selectByExampleWithBLOBs(CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    List<CascadeBase> selectByExample(CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    CascadeBaseWithBLOBs selectByPrimaryKey(String datasetid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") CascadeBaseWithBLOBs record, @Param("example") CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") CascadeBaseWithBLOBs record, @Param("example") CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int updateByExample(@Param("record") CascadeBase record, @Param("example") CascadeBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int updateByPrimaryKeySelective(CascadeBaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(CascadeBaseWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dl_cascade_cata
     *
     * @mbg.generated Tue Sep 24 11:38:54 CST 2019
     */
    int updateByPrimaryKey(CascadeBase record);
}